name: 'SecureStack Exposure Analysis'
description: 'Execute SecureStack Exposure Analysis'
inputs:
  securestack_api_key:
    description: 'SecureStack API key - generate one at https://app.securestack.com'
    required: true
  securestack_app_id:
    description: 'SecureStack Application ID - available when viewing applications at https://app.securestack.com'
    required: true
  severity:
    description: 'Severities lower than this value will not be reported - one of critical|high|medium|low'
    required: true
outputs:
  result:
    description: 'Exposure Analysis Result'
runs:
  using: 'docker'
  image: 'docker://securestackau/bloodhound-cli'
  env:
    BH_API_KEY: ${{ inputs.securestack_api_key }}
    BH_APP_ID: ${{ inputs.securestack_app_id }}
    BH_SEVERITY: 'critical'
  args:
    - recon
