on: push

jobs:
  analysis_job:
    runs-on: ubuntu-latest
    name: A job to execute analysis on an application
    steps:
      - name: Checkout repo to run secrets analysis on it
        id: checkout
        uses: actions/checkout@v2.4.0
      - name: List Project Root
        shell: bash
        run: pwd; ls -la
      - name: Secrets Analysis Step
        id: secrets
        uses: SecureStackCo/actions/secrets@main
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY_SECRET }}
          securestack_app_id: '8e9778f3-c151-4e82-a446-b945b0d3a15d'
          severity: critical
          flags: '-d 20'
